### ISSUE TITLE
Mustache does not build with GHC 9.12.2

### ISSUE THREAD

**Issue by morphismz** [JustusAdam/mustache#70]
I'm trying to build a project that depends on mustache with GHC 9.12.2, but the build fails due to the dependency on mustache. The hackage page for mustache says that it is compatible with base < 5, so I wasn't sure if this was a bug or expected behavior. 

I get the follow errors: 
```
3 of 8] Compiling Text.Mustache.Internal.Types ( src/Text/Mustache/Internal/Types.hs, dist/build/Text/Mustache/Internal/Types.o, dist/build/Text/Mustache/Internal/Types.dyn_o )
src/Text/Mustache/Internal/Types.hs:142:21: error: [GHC-87543]
    Ambiguous occurrence ‘show’.
    It could refer to
       either ‘Prelude.show’,
              imported from ‘Prelude’ at src/Text/Mustache/Internal/Types.hs:9:8-35
              (and originally defined in ‘ghc-internal-9.1202.0:GHC.Internal.Show’),
           or ‘Data.Text.show’,
              imported from ‘Data.Text’ at src/Text/Mustache/Internal/Types.hs:26:1-26.
    |
142 |   show (Object o) = show o
    |                     ^^^^

src/Text/Mustache/Internal/Types.hs:143:21: error: [GHC-87543]
    Ambiguous occurrence ‘show’.
    It could refer to
       either ‘Prelude.show’,
              imported from ‘Prelude’ at src/Text/Mustache/Internal/Types.hs:9:8-35
              (and originally defined in ‘ghc-internal-9.1202.0:GHC.Internal.Show’),
           or ‘Data.Text.show’,
              imported from ‘Data.Text’ at src/Text/Mustache/Internal/Types.hs:26:1-26.
    |
143 |   show (Array  a) = show a
    |                     ^^^^

src/Text/Mustache/Internal/Types.hs:144:21: error: [GHC-87543]
    Ambiguous occurrence ‘show’.
    It could refer to
       either ‘Prelude.show’,
              imported from ‘Prelude’ at src/Text/Mustache/Internal/Types.hs:9:8-35
              (and originally defined in ‘ghc-internal-9.1202.0:GHC.Internal.Show’),
           or ‘Data.Text.show’,
              imported from ‘Data.Text’ at src/Text/Mustache/Internal/Types.hs:26:1-26.
    |
144 |   show (String s) = show s
    |                     ^^^^

src/Text/Mustache/Internal/Types.hs:145:21: error: [GHC-87543]
    Ambiguous occurrence ‘show’.
    It could refer to
       either ‘Prelude.show’,
              imported from ‘Prelude’ at src/Text/Mustache/Internal/Types.hs:9:8-35
              (and originally defined in ‘ghc-internal-9.1202.0:GHC.Internal.Show’),
           or ‘Data.Text.show’,
              imported from ‘Data.Text’ at src/Text/Mustache/Internal/Types.hs:26:1-26.
    |
145 |   show (Number n) = show n
    |                     ^^^^

src/Text/Mustache/Internal/Types.hs:146:21: error: [GHC-87543]
    Ambiguous occurrence ‘show’.
    It could refer to
       either ‘Prelude.show’,
              imported from ‘Prelude’ at src/Text/Mustache/Internal/Types.hs:9:8-35
              (and originally defined in ‘ghc-internal-9.1202.0:GHC.Internal.Show’),
           or ‘Data.Text.show’,
              imported from ‘Data.Text’ at src/Text/Mustache/Internal/Types.hs:26:1-26.
    |
146 |   show (Bool   b) = show b
    |                     ^^^^

Error: [Cabal-7125]
Failed to build mustache-2.4.2 (which is required by exe:personal-site from personal-site-0.1.0.0). See the build log above for details.
```

**Comment by sol** [comment]
This is fixed on `master` and will be on Hackage soon.
