### ISSUE TITLE
build fails with text-2.1.2

### ISSUE THREAD

**Issue by juhp** [JustusAdam/mustache#81]
From Stackage Nightly with ghc-9.10.2

```
       Building library for mustache-2.4.2...                                                                 12:58:25 [6048/954403]
       [1 of 8] Compiling Paths_mustache                                                                                            
       [2 of 8] Compiling Text.Mustache.Internal                                                                                    
       [3 of 8] Compiling Text.Mustache.Internal.Types                                                                              
       /home/curators/work/unpack-dir/unpacked/mustache-2.4.2-f279a68aeeb8f91906ddb000a48ae36e325acf25bd8efd92759f76a18f07e951/src/T
ext/Mustache/Internal/Types.hs:142:21: error: [GHC-87543]                                                                           
           Ambiguous occurrence ‘show’.                                                                                             
           It could refer to                                                                                                        
              either ‘Prelude.show’,                                                                                                
                     imported from ‘Prelude’ at src/Text/Mustache/Internal/Types.hs:9:8-35                                          
                     (and originally defined in ‘ghc-internal-9.1002.0:GHC.Internal.Show’),                                         
                  or ‘Data.Text.show’,                                                                                              
                     imported from ‘Data.Text’ at src/Text/Mustache/Internal/Types.hs:26:1-26.                                      
           |                                                                                                                        
       142 |   show (Object o) = show o                                                                                             
           |                     ^^^^                                                                                               
        
       /home/curators/work/unpack-dir/unpacked/mustache-2.4.2-f279a68aeeb8f91906ddb000a48ae36e325acf25bd8efd92759f76a18f07e951/src/T
ext/Mustache/Internal/Types.hs:143:21: error: [GHC-87543]
           Ambiguous occurrence ‘show’.
           It could refer to
              either ‘Prelude.show’,
                     imported from ‘Prelude’ at src/Text/Mustache/Internal/Types.hs:9:8-35
                     (and originally defined in ‘ghc-internal-9.1002.0:GHC.Internal.Show’),
                  or ‘Data.Text.show’,
                     imported from ‘Data.Text’ at src/Text/Mustache/Internal/Types.hs:26:1-26.
           |
       143 |   show (Array  a) = show a
           |                     ^^^^
        
       /home/curators/work/unpack-dir/unpacked/mustache-2.4.2-f279a68aeeb8f91906ddb000a48ae36e325acf25bd8efd92759f76a18f07e951/src/T
ext/Mustache/Internal/Types.hs:144:21: error: [GHC-87543]
           Ambiguous occurrence ‘show’.
           It could refer to
              either ‘Prelude.show’,
                     imported from ‘Prelude’ at src/Text/Mustache/Internal/Types.hs:9:8-35
                     (and originally defined in ‘ghc-internal-9.1002.0:GHC.Internal.Show’),
                  or ‘Data.Text.show’,
                     imported from ‘Data.Text’ at src/Text/Mustache/Internal/Types.hs:26:1-26.
           |
       144 |   show (String s) = show s
           |                     ^^^^
:
```

**Comment by mpilgrem** [comment]
@juhp, thanks. This has been fixed in the `master` branch and there is a version that accommodates `text-2.1.2` on the blocks:
* #67 
* #68
* #72

**Comment by mpilgrem** [comment]
@jhup, `mustache-2.4.3` is released on Hackage and builds with `nightly-2025-05-06` (GHC 9.10.2).
